language: csharp
mono: none
dotnet: 2.0.0

install:
 - dotnet restore
 - npm install

script:
 - dotnet build
 - dotnet test codeartistsapi.Tests/codeartistsapi.Tests.csproj
 - npm test
 
after_success:
 - npm run report-coverage
