language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test codeartistsapi.Tests/codeartistsapi.Tests.csproj
 - sbt clean coverage test

after_success: sbt coveralls
