version: 1.0.{build}
image: Visual Studio 2017

install:
    - nuget restore
    
build:
  project: codeartistsapi.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: Xs5lc3/PPmTvmDoObEHVfTauYQtCnrhaiNkvFq5QxKhGeeR2dhQiSpVirSNepivy
 
after_test: 
# generate report for NUnit testing framework:
    - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\xunit.runner.console.2.4.0-beta.1.build3958\tools\xunit.console.exe" -targetargs:"/noshadow /domain:single codeartistsapi.Tests\bin\debug\netcoreapp2.0\codeartistsapi.Tests.dll" -output:coverage.xml        
    - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%
