version: 1.0.{build}
image: Visual Studio 2017

# to be able to do RDP on the VM where the worker is running
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
install:
    - nuget restore
    
build:
  project: codeartistsapi.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: Xs5lc3/PPmTvmDoObEHVfTauYQtCnrhaiNkvFq5QxKhGeeR2dhQiSpVirSNepivy

after_test: 
# generate report for XUnit testing framework:
    -  C:\projects\codeartists-api\packages\opencover\4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Tools\xUnit20\xunit.console.exe" -targetargs:"C:\projects\codeartists-api\codeartistsapi.Tests\bin\Debug\netcoreapp2.0\codeartistsapi.Tests.dll -noshadow" -output:".\coverage.xml" -filter:"+[*]*" 
    -  C:\projects\codeartists-api\packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

# to be able to do RDP on the VM where the worker is running on final stage (a file neews to be removed in desktop to finish the build)
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
